In [ ]:
text1 = "Ethics are built right into the ideals and objectives of the United Nations"

In [ ]:
len(text1)

75

In [ ]:
text2 = text1.split(' ')

In [ ]:
text2

['Ethics',
 'are',
 'built',
 'right',
 'into',
 'the',
 'ideals',
 'and',
 'objectives',
 'of',
 'the',
 'United',
 'Nations']

In [ ]:
len(text2)

13

In [ ]:
[w for w in text2 if len(w)>3]

['Ethics',
 'built',
 'right',
 'into',
 'ideals',
 'objectives',
 'United',
 'Nations']

In [ ]:
# Capitalized words
[w for w in text2 if w.istitle()]

['Ethics', 'United', 'Nations']

In [ ]:
# words that end with s
[w for w in text2 if w.endswith('s')]

['Ethics', 'ideals', 'objectives', 'Nations']

In [ ]:
text3 = 'To be or not to be' # findind unique words
text4  =  text3.split(' ')

In [ ]:
text4

['To', 'be', 'or', 'not', 'to', 'be']

In [ ]:
len(text4)

6

In [ ]:
len(set(text4))

5

In [ ]:
set(text4)

{'To', 'be', 'not', 'or', 'to'}

In [ ]:
len(set([w.lower() for w in text4]))

4

In [ ]:
set([w.lower() for w in text4 ])

{'be', 'not', 'or', 'to'}

In [ ]:
# some words comparison functions..
# s.startswith(t)
#s.endswith(t)
# t in s
# s.isupper() ; s.islower(); s.istitle()
# s.isalpha( ); s.isdigit(); s.isalnum()

In [ ]:
# string Operation
# s.lower()
# s.upper();
# s.titlecase();
# s.split(t)
# s.splitlines()
# s.join(t)
# s.strip()
# s.rstrip()
# s.find(t); s.rfind(t)
# s.replace(u,v)

In [ ]:
text5 = 'ouagadougou'
text6= text5.split('ou')

In [ ]:
text6

['', 'agad', 'g', '']

In [ ]:
'ou'.join(text6)

'ouagadougou'

In [ ]:
list(text5)

['o', 'u', 'a', 'g', 'a', 'd', 'o', 'u', 'g', 'o', 'u']

In [ ]:
[c for c in text5]

['o', 'u', 'a', 'g', 'a', 'd', 'o', 'u', 'g', 'o', 'u']

In [ ]:
text8 = '   A quick brown fox jumped over the lazy dog.  '

In [ ]:
text8.split(' ')

['',
 '',
 '',
 'A',
 'quick',
 'brown',
 'fox',
 'jumped',
 'over',
 'the',
 'lazy',
 'dog.',
 '',
 '']

In [ ]:
text9 = text8.strip()

In [ ]:
text9

'A quick brown fox jumped over the lazy dog.'

In [ ]:
text9.split(' ')

['A', 'quick', 'brown', 'fox', 'jumped', 'over', 'the', 'lazy', 'dog.']

In [ ]:
# changing text
# Find and replace
text9

'A quick brown fox jumped over the lazy dog.'

In [ ]:
text9.find('o')

10

In [ ]:
text9.rfind('o')

40

In [ ]:
text9.replace('o', 'O')

'A quick brOwn fOx jumped Over the lazy dOg.'

In [ ]:
# handling large texts
f=open()

FileNotFoundError: ignored

In [ ]:
f.readline()# reading line by line

'Day 13\n'

In [ ]:
# reading the full file
f.seek(0)

0

In [ ]:
text12= f.read()

In [ ]:
text12

'Day 13\n\nPortainer in docker \n\n1. docker run -itd --name web -p 7777:9000 -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer\n2. docker ps\n3. docker logs web\n4. docker logs -f web # for stop this use ctrl+c\n\nnow check your ip and enter in browser:7777\n \n\nmysql\n\n1. docker run -itd -e MYSQL_ROOT_PASSWORD=redhat -p 1122:3306  --name okdb   mysql\n2. docker ps\n3. docker logs okdb\n4. docker logs -f okdb\n5. docker exec -it okdb bash\n\t show databases;\n\t exit;\n6. docker ps\n\n\ncompose file \n \n1. mkdir /tmp/okk\n2. cd /tmp/okk\n3. vim docker-compose.yml\n    \tversion: \'3.1\'\n\tsevices:\n\t  db:\n\t    images: mysql\n\t    command: --default-authentication-plugin=mysql_native_password\n\t    restart: always\n\t    environment:\n\t      MYSQL_ROOT_PASSWORD: redhat\n\t  \n\t  adminer:\n\t     image: adminer #web server image like nginx\n             restart: always\n\t     depends_on:\n\t       - db\n              ports: \n\t\t- 8080:8080\n\npress esc then write :wp\n\n4. docker-compose up -d\n5. docker compose ps\n\nnow copy ip of your and type in browser ip:8080\n\n\n\nDay 12: ----\n\n\ndockerfile + compose\n\n1. mkdir ujjwlapp1\n2. cd ujjwalapp1 \n3. git clone https://github.com/mdn/beginner-html-site-styled\n4. ls\n5. mv beginner-html-site-styled/ web1\n6. ls\n7. vim Dockerfile\n\tFROM centos\n\tMAINTAINER ujjwalsha768@gmail.com\n\tENV x=web1\n\tRUN dnf install httpd -y\n\t# you can run dnf instead of yum\n\tADD web1 /var/www/html/\n\tEXPOSE 80\n\tENTRYPOINT httpd -DFOREGROUND\n   :wq\n\n8. ls\n9. vim docker-compose.yml\n\tversion: \'3.8\'\n\tservices:\n\t  app1:\n\t    image: ujjwal:day12v1  #here image that i want to build \n\t    build:  #location of docker file \n\t      context: .  #location of docker file\n\t      dockerfile: ujjwal.dockerfile    #name of docker file\n\t    container_name: ujjwal12c1  #pure optional field\n\t    ports: \n\t      - "9991:80"\n\t    network: \n\t      - ujjwal11  # i want to use this bridge but this is not present as of now\n\t    volumes: \n\t      - ujjwalvol12:/mnt/google  #here we are attaching it \t\n\t networks:\n\t  ujjwal11:   # this will create a new docker network\n\t \n\t volumes:\n\t  ujjwal11:   #this wil create a new volume\n\n\n\t:wq\n\n10. ls \n11. docker-compose up -d\n12. docker-compose ps\n13. docker-compose images\n14. now your ip and: 9991 in browser\n15. docker-compose down\n16. docker-compose up -d\nnow change something in your html file its not change so how to slow this type problem\n\n17.  docker-compose up --build -d\nnow again check website its change\t\t'

In [ ]:
len(text12)

2433

In [ ]:
text13 = text12.splitlines()

In [ ]:
len(text13)

113

In [ ]:
text13[0]

'Day 13'

In [ ]:
# file operatios
# f= open(filename,  mode)
# f.readlie();f.read(); f.read(n)
# for line in f: doSomething(line)
# f.seek()
# f.write(message)
# f.close()
# f.closed

In [ ]:
f = open('C:\\Users\\ujjwal\\Desktop\\docker.txt', 'r')

In [ ]:
text14 = f.readline()

In [ ]:
text14 # issues with reading text files

'Day 13\n'

In [ ]:
# how do you remove the last newline character ?
text14.rstrip()

'Day 13'

In [ ]:
# Processing free-text
text15 = '"Ethics are built right into the ideals and objectives of the United Nations" \
#UNSG @ NY Society for Ethical Culture bit.ly/2guVelr'

In [ ]:
text16 = text15.split(' ')

In [ ]:
text16

['"Ethics',
 'are',
 'built',
 'right',
 'into',
 'the',
 'ideals',
 'and',
 'objectives',
 'of',
 'the',
 'United',
 'Nations"',
 '#UNSG',
 '@',
 'NY',
 'Society',
 'for',
 'Ethical',
 'Culture',
 'bit.ly/2guVelr']

In [ ]:
[w for w in text16 if w.startswith('#')] # fiding hastags

['#UNSG']

In [ ]:
[w for w in text16 if w.startswith('@')]

['@']

In [ ]:
text17 = '@UN @UN_Women "Ethics are built right into the ideals and objectives of the United Nations" \#UNSG @ NY Society for Ethical Culture bit.ly/2guVelr'
text18 = text17.split(' ')

In [ ]:
text18

['@UN',
 '@UN_Women',
 '"Ethics',
 'are',
 'built',
 'right',
 'into',
 'the',
 'ideals',
 'and',
 'objectives',
 'of',
 'the',
 'United',
 'Nations"',
 '\\#UNSG',
 '@',
 'NY',
 'Society',
 'for',
 'Ethical',
 'Culture',
 'bit.ly/2guVelr']

In [ ]:
#We can use regular expressions to help us with more complex parsing.

#For example '@[A-Za-z0-9_]+' will return all words that:

#start with '@' and are followed by at least one:
#capital letter ('A-Z')
#lowercase letter ('a-z')
#number ('0-9')
#or underscore ('_')

In [ ]:
#import re  # import re - a module that provides support for regular expressions
#[w for w in text18 if re.search('@[A-Za-z0-9_]+',w)]



##########
#######  Meta-chacters: Character matches

#  . "wildcaard, matches a single character"
#  ^ "start of a string"
# $ "end of a string"
# [] "matches one of the set of character within []"
# [a-z] "matches one of the range of chacarters a,b,c,....z"
# [^abc] "matches a character that is not a,b, or c "
# a|b "matches either a or  b, where a and b are strings"
# () "Scoping for opertors"
# \ "Escape character for special character (\t,\n,\b)"

##########
#######  Meta-chacters: Character symbols

#  \b "matches word boundary"
#  \d "any digit, equivalent to [0-9]"
#   \D "any non-digit, equivalent to [^0-9]"
#  \s "any white space, equivalent to [ \t \n \r \f \v]"
#  \S "any non-white space, equivalent to[^ \t\n\r\f\v]"
# \w "Alphaumeric character , equivalent to[a-zA-Z0-9_]"
# \W " non-alphanumeric, equivalent to[^a-zA-Z0-9_]"


##########
#######  Meta-chacters: Repetitios

# * "matches zero or more occurreces"
# + " MATCHES one or more occurrences"
# ? "Matches zero or more occurrences"
# {n} "exactly n repetitions"
# {n,} "at least n repetitions"
# {,n} " at most n repetitions"
# {m,n} "at least m and at most n repetitions"

#[w for w in text18 if re.search('@\w+' , w)]

In [ ]:
#finding special charcter
import re
text20 = 'ousnduiuela'
re.findall(r'[aeiou]',text20)

['o', 'u', 'u', 'i', 'u', 'e', 'a']

In [ ]:
re.findall(r'[^aeiou]',text20)

['s', 'n', 'd', 'l']

In [ ]:
#regular expression for  dates
dateStr = '23-10-2002\n23/10/2002\n23/10/02\n10/23/2002\n23 Oct 2002\n23 October 2002\nOct 23,2002\nOctober 23,2002\n'

In [ ]:
re.findall(r'\d{2}[/-]\d{2}[/-]\d{4}',dateStr)

['23-10-2002', '23/10/2002', '10/23/2002']

In [ ]:
re.findall(r'\d{2}[/-]\d{2}[/-]\d{2,4}',dateStr)

['23-10-2002', '23/10/2002', '23/10/02', '10/23/2002']

In [ ]:
re.findall(r'\d{1,2}[/-]\d{1,2}[/-]\d{2,4}',dateStr)

['23-10-2002', '23/10/2002', '23/10/02', '10/23/2002']

In [ ]:
#Regex for Dates(Contd.)
re.findall(r'\d{2} (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4}',dateStr)

['Oct']

In [ ]:
re.findall(r'\d{2} (?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4}',dateStr)

['23 Oct 2002']

In [ ]:
re.findall(r'\d{2} (?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* \d{4}',dateStr)

['23 Oct 2002', '23 October 2002']

In [ ]:
re.findall(r'(?:\d{2} )?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* (?:\d{2},)?\d{4}', dateStr)

['23 Oct 2002', '23 October 2002', 'Oct 23,2002', 'October 23,2002']

In [ ]:
re.findall(r'(?:\d{1,2} )?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* (?:\d{1,2},)?\d{4}', dateStr)

['23 Oct 2002', '23 October 2002', 'Oct 23,2002', 'October 23,2002']

In [ ]:
#Working with Text Data in pandas

import pandas as pd

In [ ]:
time_sentences = ["Monday: The doctor's appointment is at 2:45pm.",
                  "Tuesday: The dentist's appointment is at 11:30 am.",
                  "Wednesday: At 7:00pm, there is a basketball game!",
                  "Thursday: Be back home by 11:15 pm at the latest.",
                  "Friday: Take the train at 08:10 am, arrive at 09:00am."]

df = pd.DataFrame(time_sentences, columns=['text'])
df

                                                text
0     Monday: The doctor's appointment is at 2:45pm.
1  Tuesday: The dentist's appointment is at 11:30...
2  Wednesday: At 7:00pm, there is a basketball game!
3  Thursday: Be back home by 11:15 pm at the latest.
4  Friday: Take the train at 08:10 am, arrive at ...

In [ ]:
# find the number of characters for each string in df['text']
df['text'].str.len()

0    46
1    50
2    49
3    49
4    54
Name: text, dtype: int64

In [ ]:
# find the number of tokens for each string in df['text']
df['text'].str.split().str.len()

0     7
1     8
2     8
3    10
4    10
Name: text, dtype: int64

In [ ]:
# find which entries contain the word 'appointment'
df['text'].str.contains('appointment')

0     True
1     True
2    False
3    False
4    False
Name: text, dtype: bool

In [ ]:
# find how many times a digit occurs in each string
df['text'].str.count(r'\d')

0    3
1    4
2    3
3    4
4    8
Name: text, dtype: int64

In [ ]:
# find all occurances of the digits
df['text'].str.findall(r'\d')

0                   [2, 4, 5]
1                [1, 1, 3, 0]
2                   [7, 0, 0]
3                [1, 1, 1, 5]
4    [0, 8, 1, 0, 0, 9, 0, 0]
Name: text, dtype: object

In [ ]:
# group and find the hours and minutes
df['text'].str.findall(r'(\d?\d):(\d\d)')

0               [(2, 45)]
1              [(11, 30)]
2               [(7, 00)]
3              [(11, 15)]
4    [(08, 10), (09, 00)]
Name: text, dtype: object

In [ ]:
# replace weekdays with '???'
df['text'].str.replace(r'\w+day\b', '???')

0          ???: The doctor's appointment is at 2:45pm.
1       ???: The dentist's appointment is at 11:30 am.
2          ???: At 7:00pm, there is a basketball game!
3         ???: Be back home by 11:15 pm at the latest.
4    ???: Take the train at 08:10 am, arrive at 09:...
Name: text, dtype: object

In [ ]:
# replace weekdays with 3 letter abbrevations
df['text'].str.replace(r'(\w+day\b)', lambda x: x.groups()[0][:3])

0          Mon: The doctor's appointment is at 2:45pm.
1       Tue: The dentist's appointment is at 11:30 am.
2          Wed: At 7:00pm, there is a basketball game!
3         Thu: Be back home by 11:15 pm at the latest.
4    Fri: Take the train at 08:10 am, arrive at 09:...
Name: text, dtype: object

In [ ]:
# create new columns from first match of extracted groups
df['text'].str.extract(r'(\d?\d):(\d\d)')

    0   1
0   2  45
1  11  30
2   7  00
3  11  15
4  08  10

In [ ]:
# extract the entire time, the hours, the minutes, and the period
df['text'].str.extractall(r'((\d?\d):(\d\d) ?([ap]m))')

                0   1   2   3
  match
0 0        2:45pm   2  45  pm
1 0      11:30 am  11  30  am
2 0        7:00pm   7  00  pm
3 0      11:15 pm  11  15  pm
4 0      08:10 am  08  10  am
  1       09:00am  09  00  am

In [ ]:
# extract the entire time, the hours, the minutes, and the period with group names
df['text'].str.extractall(r'(?P<time>(?P<hour>\d?\d):(?P<minute>\d\d) ?(?P<period>[ap]m))')

             time hour minute period
  match
0 0        2:45pm    2     45     pm
1 0      11:30 am   11     30     am
2 0        7:00pm    7     00     pm
3 0      11:15 pm   11     15     pm
4 0      08:10 am   08     10     am
  1       09:00am   09     00     am